
dx: 0.04
dy: 0.04

checkerboard_rows: 9
checkerboard_cols: 6

min_points_on_plane: 165
max_points_on_plane: 800

num_views: 10
num_of_initializations: 1

x_min: 1
x_max: 3
y_min: -1.5
y_max: 1.5
z_min: -0.3
z_max: 1

ransac_threshold: 0.01

sor_mean_k: 50
sor_std_dev: 1.0